import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import {
  Box,
  Drawer,
  DrawerContent,
  DrawerOverlay,
  HStack,
  useDisclosure,
  Flex,
  SimpleGrid,
  VStack,
  Tabs,
  TabList,
  TabPanels,
  Tab,
  TabPanel,
} from "@chakra-ui/react";
const inter = Inter({ subsets: ["latin"] });
import Explore from "@/containers/Home/Explore";
import DataExplore from "@/containers/Home/DataExplore";
import Overview from "@/containers/Home/Overview";
import Integrate from "@/containers/Home/Integrate";
export default function Home() {
  return (
    <>
      <Head>
        <title>Bravos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <VStack w={"100%"} top={0}>
        <Tabs w={"100%"}>
          <TabList>
            <Tab>Overview</Tab>
            <Tab>Explore</Tab>
            <Tab>Data Explore</Tab>
            <Tab>Integrate</Tab>
          </TabList>
          <TabPanels>
            <TabPanel w={"100%"}>
              <Overview />
            </TabPanel>
            <TabPanel>
              <Explore />
            </TabPanel>
            <TabPanel>
              <DataExplore />
            </TabPanel>
            <TabPanel>
              <Integrate />
            </TabPanel>
          </TabPanels>
        </Tabs>
      </VStack>
    </>
  );
}
